### ISSUE TITLE
Requires changes for XCode 10/Mojave

### ISSUE THREAD

**Issue by papley** [RNCryptor/RNCryptor#274] opened 2018-06-12 20:47 UTC
XCode 10 is unhappy about what it sees as duplicate declarations for many of the constants, many of which can be found in CommonCrypto/CommonHMAC.h.
There are several other issues as well.
I have a hack that allows me to use RNCryptor in the new environment, but I have not conditionalized it to still work in the old environment. It is also not necessarily the best way to fix it. However I can provide what I have for review.

**Comment by rnapier** [comment] 2018-06-12 20:55
Interesting; I'm not seeing this issue in Xcode 10 on High Sierra. Is it only happening on Mojave?

Did you add `import CommonCrypto` somewhere else? I can force errors by adding that, but I'm not seeing any errors in the standard build.

**Comment by papley** [comment] 2018-06-12 22:28
We were unable to include the cocoapod in our project under XCode 10 and High Sierra. 
Actually, #import <CommonCrypto/CommonCrypto.h> was in our bridging header, but I had to move it to your header to stop the conflict. I don't understand how they can coexist at all.

**Comment by rnapier** [comment] 2018-06-12 22:37
I can't reproduce what you're describing so far. I did the following:

* Create a new iOS project
* pod init
* Add `pod 'RNCryptor'` to Podfile
* pod install
* Open workspace
* Build

I then added `import RNCryptor` to my AppDelegate, and created a cryptor. Still builds without trouble.

What Cocoapods issues are you seeing?

**Comment by papley** [comment] 2018-06-13 14:30
The first error I corrected was this below. My bridging header follows below that.

![first error in rncryptor](https://user-images.githubusercontent.com/1513087/41357484-465dc1e8-6ef4-11e8-95b2-91a4cd73e661.png)


//
//  Leash-Bridging-Header.h
//  LeashClient
//
//  Created by USR ID, Inc. on 2/22/16.
//  Copyright © 2016 Universal Secure Registry, LLC. All rights reserved.
//

#ifndef Leash_Bridging_Header_h
#define Leash_Bridging_Header_h

//#import <CommonCrypto/CommonCrypto.h>
@import CocoaLumberjack;
#import "USR_LTLoginViewController.h"
#import "USR_LTConfirmViewController.h"
#import "USR_LTLockViewController.h"
#import "RNCryptor/RNCryptor.h"
#import "USR_LTLockViewController.h"
#import "CrashlyticsLogger.h"
#import "UIViewController+ResizingTitle.h"
#import "DetailLogFormatter.h"
#import "USR_LTBaseViewController.h"
#import "BCryptWrapper.h"
#import "USR_LTBiometric.h"
#import "USR_LTErrorHandler.h"
#import "TouchIDCheck.h"
#import "USR_LTAuditLog.h"

#endif /* Leash_Bridging_Header_h */

**Comment by papley** [comment] 2018-06-13 14:45
This was fixed with this:

        public static func makeKey(forPassword password: String, withSalt salt: Data) -> Data {

            var derivedKey = Data(count: keySize)!
            let passwordData = password.data(using: String.Encoding.utf8)!

            let result: CCCryptorStatus = derivedKey.withUnsafeMutableBytes {
                (derivedKeyPtr : UnsafeMutablePointer<UInt8>) in
                passwordData.withUnsafeBytes { (passwordPtr : UnsafePointer<Int8>) in
                    salt.withUnsafeBytes { (saltPtr : UnsafePointer<UInt8>) in

                        // All the crazy casting because CommonCryptor hates Swift
                        let algorithm     = CCPBKDFAlgorithm(kCCPBKDF2)
                        let prf           = CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA1)
                        let pbkdf2Rounds  = UInt32(10000)

                        return CCCryptorStatus(
                            CCKeyDerivationPBKDF(
                            algorithm,
                            passwordPtr,   passwordData.count,
                            saltPtr,       salt.count,
                            prf,           pbkdf2Rounds,
                            derivedKeyPtr, keySize)
                        )
                    }
                }
            }

            guard result == CCCryptorStatus(kCCSuccess) else {
                fatalError("SECURITY FAILURE: Could not derive secure password (\(result)).") // : \(derivedKey)
            }
            return derivedKey
        }

**Comment by rnapier** [comment] 2018-06-13 20:23
What’s confusing me here is this is a bug I fixed in 5.0.3. I have a feeling you’re basing your work on a copy of 5.0.2.

**Comment by papley** [comment] 2018-06-13 22:16
Sorry, this is really important to us to figure out in the next week or so, but I have other emergencies, and going through all the commits trying to figure out the sequence of issues in our project (not RNCryptor) is complicated because the commits are pretty dense.

**Comment by papley** [comment] 2018-06-13 22:17
No. We're using 5.0.3.

**Comment by papley** [comment] 2018-06-13 22:17
And it works fine before Xcode 10.

**Comment by rnapier** [comment] 2018-06-14 14:38
I can't reproduce this so far on Xcode 10, and the PR you provided appears based on 5.0.2 (I'd commented on the PR but forgot to submit it; check out the PR now). Do you have a project I can see that demonstrates this issue?

**Comment by papley** [comment] 2018-06-14 21:02
You were right. Even though we were specifying 5.0.3 we were getting 5.0.2 because we had a Podfile.lock that was causing our Podfile to be ignored. That and several other problems which were causing reference loops into other cocoapods caused your Pod to be blamed. Once we switched to 5.0.3 and removed a reference into a CocoaLumberjack macro definition, and removed 

#import "RNCryptor/RNCryptor.h"
in favor of 
#import <CommonCrypto/CommonCrypto.h>

in our bridging headers, everything works in all 4 permutations of XCODE 9, XCODE 10, and High Sierra, Mojave, on Mac and iOS.

So sorry to raise a false alarm, and thanks for the hint about 5.0.3. I might have missed it a while longer if you hadn't mentioned it.

**Closed** 2018-06-14 21:03 UTC
