### ISSUE TITLE
Update to Xcode 8 beta 6

### ISSUE THREAD

**Issue by jasonhocker** [RNCryptor/RNCryptor#201] opened 2016-08-19 14:53 UTC
Here are the new errors in Xcode 8 beta 6

RNCryptor.swift:183:24: Use of unresolved identifier 'oneshot'
RNCryptor.swift:323:25: Use of unresolved identifier 'oneshot'
RNCryptor.swift:398:28: Property 'preambleSize' must be as accessible as its enclosing type because it matches a requirement in protocol 'VersionedDecryptorType'
RNCryptor.swift:399:29: Method 'canDecrypt(preamble:)' must be as accessible as its enclosing type because it matches a requirement in protocol 'VersionedDecryptorType'
RNCryptor.swift:434:24: Use of unresolved identifier 'oneshot'
RNCryptor.swift:781:36: Cannot invoke initializer for type 'UnsafeMutablePointer<UInt8>' with an argument list of type '(UnsafeMutableRawPointer)'

**Comment by rnapier** [comment] 2016-08-19 15:51
In progress fixing these, but haven't pushed because I need to do a much larger change to work w/ Swift 3. Swift 3 will ship with a bug that breaks RNCryptor's ObjC bridging (the Swift team has already confirmed it's a bug and they're not fixing it yet), so I need to rework some things to avoid that.

**Comment by jasonhocker** [comment] 2016-08-25 13:50
Do you have that issue recorded here?  Want to make sure this isn't a bug that affects us that we haven't observed yet.

**Comment by rnapier** [comment] 2016-08-25 13:56
See https://bugs.swift.org/browse/SR-2267.

Currently you cannot call RNCryptor from ObjC if built for Swift 3. This will show up as a linker error, so it won't bite you at runtime. If your program links, it will work.

**Comment by bassrock** [comment] 2016-09-11 18:42
Any help any of us can be with the swift3.0? Need to update one of my apps that use RNCryptor.

**Comment by rnapier** [comment] 2016-09-11 23:35
I just pushed fix for that to the swift3 branch. Tomorrow I'll tag and release it, but feel free to take a look now and let me know if there are any problems. I had to pull ObjC bridging for now. There are just too many weird compiler issues. I've pulled an ObjC-specific version into a new repo.

**Comment by rnapier** [comment] 2016-09-16 15:55
This should be fixed in the latest 5.0 release.

**Closed by rnapier** 2016-09-16 15:55 UTC
